# Learning During a Pandemic

The CWRU Return to Campus website is found at https://case.edu/return-to-campus/.

Life is not OK right now. None of us are really okay. We're all just pretending.

You most likely know people who have lost their jobs, have tested positive for COVID-19, have been hospitalized, or perhaps have even died. You all have increased (or possibly decreased) work responsibilities and increased  care responsibilities - you might be caring for extra people (young and/or old!) right now, and you might be facing uncertain job prospects.

I'm fully committed to making sure that you learn everything you were hoping to learn from this class! I will make whatever accommodations I can to help you finish your labs, do well on your essays and projects, and learn and understand the class material. Under ordinary conditions, I am somewhat flexible and lenient with grading and course expectations when students face difficult challenges. Under pandemic conditions, that flexibility and leniency is intensified. If you tell me you're having trouble, I will not judge you or think less of you. I hope you'll extend me the same grace.

You never owe me personal information about your health (mental or physical). You are always welcome to talk to me about things that you're going through, though. If I can't help you myself, I may know somebody who can.

If you need extra help, or if you need more time with something, or if you feel like you're behind or not understanding everything, do not suffer in silence! Talk to us! We will work with you. I promise.

I want you to learn lots of things from this class, but I primarily want you to stay healthy, balanced, and grounded during this crisis.

Thanks to [Andrew Heiss](https://econf20.classes.andrewheiss.com/syllabus/#learning-during-a-pandemic) for a lot of the better words here.

## In case of emergency

What if my situation changes (for any reason) during the semester?

If you need to miss one session, or even two, just review the materials (including the recordings) and move on, and please feel encouraged to ask for help.

If an emergency arises that will keep you from timely completion of a lab, essay, presentation or project, send an email directly to Dr. Love saying the following:

> I have an emergency that will keep me from completing (*list things you're worried about completing*) in a timely fashion. I will contact you again when I am able to make plans.

- Dr. Love will respond with "OK" and temporarily excuse you from things until **you** send a "re-connection" email to make plans for making up the work you missed, at which time he'll evaluate the situation and together you can make that plan. At no time do you owe us any information about your health or the nature of the emergency.

